### ISSUE TITLE
Whoops!

### ISSUE THREAD

**Issue by Plazmaz** [goloroden/jsdays-2017#1]
Looks like you uploaded your MongoDB info: https://github.com/goloroden/jsdays-2017/blob/master/nodejs/app.js
You should probably remove that and change the credentials for mongo.

**Comment by Plazmaz** [comment]
Also, if that server is used for production, you should use a more secure password.

**Comment by goloroden** [comment]
Thanks for the hint, but this is not a problem, as the MongoDB database is not online any more (and it was not online any more, when the commit was made).

Thanks anyway :-)
